### PR TITLE
feat: close popconfirm when click outside and improve directive #658

### LINKED ISSUE #657: fix: popconfirm should close automatically when user interact with pagination
[Screencast from 2023-05-22 09-49-00.webm](https://github.com/Brisanet/ion/assets/57760325/d8bdaad0-3bf8-4be5-8cdc-30a8b1880936)

### LINKED ISSUE #658: feat: close when click outside on popconfirm
We should be able to close popconfirm when user click outside it (similar to the feature that was implemented here: https://github.com/Brisanet/ion/pull/620).
We also should be able to choose if the popconfirm will have this behaviour.

Example:
[Kazam_screencast_00000.webm](https://github.com/Brisanet/ion/assets/57760325/0ffa55ab-6b7b-4af0-bdb0-42929932e3c2)

### PR DESCRIPTION
**Pull request by iurynogueira**
## Issue Number

fix #658
fix #657

## Description

This PR change too remove firstOpen flag from button/dropdown and fix popconfirm close when clickout side.

## How to Test

You can check on button with dropdown clicking in outside element and too you can repeat this same behavior in smart table when open a popconfirm from action.

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

### CODE REVIEW

**Comment by AlyssonMascarenhas** [comment]
I was testing it in the storybook, and I saw that when opening a popconfirm in the ion-smart-table and closing it, I couldn't but open it again through the action button. Has this behavior happened to you?
[evidencia-PR670.webm](https://github.com/Brisanet/ion/assets/54484070/0bc068ad-3a3e-4676-9e04-00fe887aa4a7)

**Comment by iurynogueira** [comment]
> I was testing it in the storybook, and I saw that when opening a popconfirm in the ion-smart-table and closing it, I couldn't but open it again through the action button. Has this behavior happened to you? [evidencia-PR670.webm](https://github.com/Brisanet/ion/assets/54484070/0bc068ad-3a3e-4676-9e04-00fe887aa4a7)

😮 I will check this

**Comment by iurynogueira** [comment]
> Error happend when do double click in button

fixed in last commit

**Review by mizek1 — APPROVED** [review]
Thank you, it solved our problem on SIGA! 😄

**Pull request merged**
