### PR TITLE
feat: popover without header

### LINKED ISSUE #1037: feat: popover without header
Add variation to the popover without its header

### PR DESCRIPTION
**Pull request by allan-chagas-brisa**
## Issue Number

fix #1037 

## Description

Now when user doesnt provide a title to the popover it renders without the header and with a customized style.

## Proposed Changes

- Popover without the header;
- Scrollbar style fixed.

## Screenshots

image
Captura de tela de 2024-04-11 13-47-12

## Compliance

- [X] I have verified that this change complies with our code and contribution policies.
- [X] I have verified that this change does not cause regressions and does not affect other parts of the code.

### CODE REVIEW

**Review by wermeson-lopes-brisa — APPROVED** [review]

**Review by pedro-martins-brisa — APPROVED** [review]
I think the ionPopoverTitle typing is not optional, it would be good to change it in PopoverProps

**Comment by allan-chagas-brisa** [comment]
> I think the ionPopoverTitle typing is not optional, it would be good to change it in PopoverProps

Its Optional now at least, when you dont pass it, it will render this "without header mode"

**Comment by allan-chagas-brisa** [comment]
> Reference in

I'll work on it

**Comment by allan-chagas-brisa** [comment]
> I think it would be interesting to create a page in storybook for this.

I'll work on it

**Review by danilo-moreira-brisa — APPROVED** [review]

**Pull request merged**
